--- 
javascripts: 
- base: 
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - tabber
  - boxover
  - redbox
stylesheets: 
- base:
  - reset-fonts
  - styles
  - redbox
  - rounded-corners
  - ratings
  
