--- 
javascripts: 
- base: 
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - tabber
  - boxover
  - redbox
stylesheets: 
- base:
  - reset-min
  - styles
  - redbox
  - rounded-corners
  
