test:
  namespace: biocat_trunk2_test
  servers: 127.0.0.1:11211
  
development:
  namespace: biocat_trunk2_dev
  servers: 127.0.0.1:11211
  
production:
  namespace: biocat_trunk2_prod
  servers: 127.0.0.1:11211